---
title: "00_Data_preprocess"
---

# 01.Load Packages and files
```{r}
library(modelr)
library(mice)
library(VIM)
library(DMwR2)
library(rpart)
library(car)
library(splines)
library(gam)
library(caret)

source('defined_functions.R')
data_MCPD = read.csv('00_Data/data_MCPD.csv') # Generated from STATA files

colnames(data_MCPD)
```

# 02.Pre-process data
## Define and transform
```{r}
# Define Catogory Variables
data_MCPD$SEX<-as.factor(data_MCPD$SEX)
data_MCPD$FAMINCOM5w<-as.factor(data_MCPD$FAMINCOM5w)
data_MCPD$SMOKE<-as.factor(data_MCPD$SMOKE)
data_MCPD$MARRIAGE<-as.factor(data_MCPD$MARRIAGE)
data_MCPD$education<-as.factor(data_MCPD$education)
data_MCPD$alcohol<-as.factor(data_MCPD$alcohol)
data_MCPD$CVD<-as.factor(data_MCPD$CVD)
data_MCPD$db<-as.factor(data_MCPD$db)
data_MCPD$HBP<-as.factor(data_MCPD$HBP)

# Log-Transformed for exposure and response variable (i.e. outcome)
data_MCPD$dietaryMCPD <- log(data_MCPD$dietaryMCPD)
data_MCPD$DHPMA_a <- log(data_MCPD$DHPMA_a)

# Scaled Quantitive variables
data_MCPD[1:12]<- scale(data_MCPD[1:12],center=F,scale=T)

# Exclude outlier in the response variable.
list = c()
value <- data_MCPD$dietaryMCPD
QL <- quantile(value, probs = 0.25)
QU <- quantile(value, probs = 0.75)
a <- which(value > QU + 1.5*(QU-QL)) 
b <- which(value < QL - 1.5*(QU-QL)) 
temp <- append(a,b)
list <- append(list, temp)
list <- list[!duplicated(list)]
data_MCPD <- data_MCPD[-list,]
```

## Normality test
```{r}
library(nortest)
lillie.test(data_MCPD$dietaryMCPD)
hist(data_MCPD$dietaryMCPD)
```

## Selection by Lasso
```{r}
pdf('01_Output_Results/Figure1-3.pdf')
library(glmnet)
x = model.matrix(dietaryMCPD~.,data_MCPD)
y = data_MCPD$dietaryMCPD

grid = 10^seq(5,-5,length=20)
lasso.model = glmnet(x,y, alpha=1, lambda=grid)
cv.out <- cv.glmnet(x,y,alpha=1)
bestlam <- cv.out$lambda.min
lam_1se <- cv.out$lambda.1se
lasso.pred <- predict(lasso.model, s = bestlam, newx = x)
lasso.coef = predict(lasso.model, type = 'coefficients', s = bestlam)
# lasso.coef
plot(lasso.model)
plot(cv.out)

dev.off()

lasso.coef # Exclude variables whose s1 value is '.', WEIGHT
```

# 03.MLR Models
## Fitted results
```{r}
model.MLR1 <-lm(dietaryMCPD ~ age+SEX+education+MARRIAGE+alcohol+SMOKE
                  +FAMINCOM5w
                  +DHPMA_a, 
                  data = data_MCPD)

model.MLR2 <-lm(dietaryMCPD ~ age+SEX+education+MARRIAGE+alcohol+SMOKE
                +FAMINCOM5w
                +HEIGHT+BMI+CREATININE+MET+CVD+HBP+MET+db+HBP
                +DHPMA_a, 
                data = data_MCPD)

model.MLR3 <-lm(dietaryMCPD ~ age+SEX+education+MARRIAGE+alcohol+SMOKE
                +FAMINCOM5w
                +HEIGHT+BMI+CREATININE+MET+CVD+HBP+MET+db+HBP
                +totalenergy+BEANOILintake+PEANUTOIintake+LARDOILintake
                +DHPMA_a, 
                data = data_MCPD)

# summary(model.MLR1)
# summary(model.MLR2)
# summary(model.MLR3)
```

## Check Co-linearity
```{r}
vif(model.MLR3) # No
```

## Interaction between DHPMA and co-varaites
```{r}
colnames(data_MCPD)
varList <- c("CREATININE","HEIGHT","BMI","age","BEANOILintake",
             "PEANUTOIintake","LARDOILintake","MET","totalenergy",'db',
             "MARRIAGE","SMOKE","SEX","FAMINCOM5w","CVD","HBP","alcohol","education")

## Interaction Check
results_BA_CES <- data.frame(Estimate = NA,
                             SE = NA,
                             T.value = NA,
                             P_value = NA)
for (var in varList){
  formula = as.formula(paste0('dietaryMCPD~ ',var,'+.+DHPMA_a:', var))
  fit <- lm(formula, data_MCPD)
  a = summary(fit); tmp = data.frame(a$coefficients)
  colnames(tmp) = c('Estimate', 'SE', 'T.value', 'P_value')
  results_BA_CES = rbind(results_BA_CES, tmp[c(2,25:dim(tmp)[1]),])
  #print(i);print(summary(fit1))
}
results_BA_CES
```

# 04.GAM, SVR and RF Model
## GAM Model
### Check Non-linearity
```{r}
model.gam1 <- gam(dietaryMCPD~s(CREATININE)+s(HEIGHT)+s(BMI)+s(age)+s(BEANOILintake)
                             +s(PEANUTOIintake)+s(LARDOILintake)+s(MET)+s(DHPMA_a)
                             +s(totalenergy)+MARRIAGE+SEX+FAMINCOM5w+CVD+SMOKE          
                             +HBP+alcohol+education, data = data_MCPD)
summary(model.gam1)
# CREATININE,age,BEANOILintake,PEANUTOIintake,LARDOILintake,totalenergy shows non-linearity characteristics.
```

### Re-fit Model
```{r}
model.gam2 <- lm(dietaryMCPD~s(CREATININE)+HEIGHT+BMI+s(age)+s(BEANOILintake)
                 +s(PEANUTOIintake)+s(LARDOILintake)+MET+DHPMA_a
                 +s(totalenergy)+MARRIAGE+SEX+FAMINCOM5w+CVD      
                 +HBP+alcohol+education, data = data_MCPD)
summary(model.gam2)
```

## SVR Model
```{r}
library(e1071)
model.svm <- svm(dietaryMCPD~., kernal = 'radial basis',type = 'eps-regression',data=data_MCPD)
summary(model.svm)
# defaultSummary(data.frame(obs = data_MCPD$dietaryMCPD, pred = predict(model.svm, data = data_MCPD)))
```

## RF Model
```{r}
set.seed(205)
library(randomForest)
pdf('01_Output_Results/RandomForest_var.pdf')
model.RF <- randomForest(dietaryMCPD~., 
                         mtry = 5, data=data_MCPD, importance = TRUE, ntree=500)
varImpPlot(model.RF) # MeanDecreaseGini
dev.off()

defaultSummary(data.frame(obs = data_MCPD$dietaryMCPD, pred = predict(model.RF, data = data_MCPD)))
importance(model.RF)
```

## 